### ISSUE TITLE
do you want the website domain still?

### ISSUE THREAD

**Issue by sckott** [pdxrlang/pdxrlang#11]
pdxrlang.com is expiring in 30 days. Do you want a different domain or just use github pages/netlify?

**Comment by sckott** [comment]
@buchmayne @laderast

**Comment by laderast** [comment]
Hi Scott,

Yes, we want the domain - we've been rebuilding the website as a hugo/netlify page, so if we can transfer ownership, that would be good.

**Comment by sckott** [comment]
Not transferred a domain before. Do either of you have a namecheap account? Or another account where you manage domains?

**Comment by laderast** [comment]
I do have a namecheap account - we can work on this tonight or after work one day - kind of busy right now

**Comment by sckott** [comment]
Whenever you want. Just need to do it within the next month

**Comment by laderast** [comment]
Ok - I have time tomorrow (Weds) - I’ll contact you by slack
